[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-fund --silent"

# Redirect configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
