[build]
  publish = "build"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- backend/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-fund --silent"
  # Frontend-only build - disable secrets scanning
  SECRETS_SCAN_ENABLED = "false"
  # Clear any backend environment variables
  DATABASE_URL = ""
  JWT_SECRET = ""
  COOKIE_SECRET = ""

# Single Page Application redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
